### PR TITLE
Ensure animations are rendered in their final state.

### PR DESCRIPTION
**Pull request by gpoesia**
This eliminates the effect of small pauses in the final state of the animation. A glitch could cause an element not to be updated in the final state of the animation because it could go from active (before its end_time) to inactive (after its end_time) without ever being updated at its end_time.

### CODE REVIEW

**Comment by gpoesia** [comment]
Puts this PR on hold for a while. I have a slightly better fix, will update it tomorrow.

**Comment by gpoesia** [comment]
Ready for review.

**Comment by vrod** [comment]
approve

**Comment by dilsonguim** [comment]
approve

**Pull request closed without merging**
